---
title: The prevalence of bad matrix models
author: Bruce Kendall
date: '2018-03-15'
slug: the-prevalence-of-bad-matrix-models
categories:
  - Science
tags:
  - bad matrix models
---

My students in 211 have revealed that there are an astonishing number of animal population matrices still being published with fundamental errors, including no survival in the reproductive term, failing to hit first breeding in models with post-breeding censuses, and incorrect maturation fractions in stage-for-age models (basically, if stage duration is T, they say that the maturation fraction is $1/T$). A quick analysis I did on the lionfish model shows that the latter has the biggest impact on $\lambda$ (1.14 vs 1.03). I would suspect that there are similarly sized impacts on other life history variables (generation time etc).

I think I should write a short paper pointing this out and extracting the frequency of errors in comadre/compadre—-perhaps also looking at trends through time. The new special issue that Rob just circulated about would be a good venue. The paper might also need to explore the impacts of T, juvenile survival and lambda on the error associated with this error.

To do this, I need to identify within the databases the studies that use post-breeding censuses and that use stage-structured models. For the former, I can look at the names of the first stage class (at least for animals; I’ll need to think some more about plants), in MatrixClassAuthor. There will be some cases that are still ambiguous, but a few months ago I looked at this and there were a lot of examples of “age0”, “neonate” etc.

For the second, the variable “MatrixCriteriaOntogeny” might be a guideline.

I’d then need to go to the actual papers to find out how the matrices were constructed from underlying data, (although for the maturation data I could do a first cut by looking at whether $P_i$ is an integer multiple of $G_i$). This is the time consuming bit.

I anticipate adding several variables to the database:

- Census type (pre, post, other)
- Survival included in reproductive transition (Yes, no, unclear)
- Stage4Age (yes, no; maybe list which stage classes; NA for size and age-only models)
- MaturationModel (1/T, Crowder, others?)

The abstract is due by the end of the month. For that purpose, I think I need to do a preliminary count of post-breeding and stage structured models, and then look at a sample of them for frequencies. In my cover letter to Rob I’ll mention that the numbers will change as I make a more comprehensive list.

Note that there is a rudimentary package on github at `jonesor/compadreDB/mage`. It includes a function for assembling a life table from a stage structured model that *assumes* that the maturation fraction is correct!
